export const CHANGE_BUY_SYSTEM = 'CHANGE_BUY_SYSTEM';
export const CHANGE_SELL_SYSTEM = 'CHANGE_SELL_SYSTEM';
export const CHANGE_TAX = 'CHANGE_TAX';
export const LOAD_PRICES_BY_SYSTEMS = 'LOAD_PRICES_BY_SYSTEMS';